Added links to each user to the personal table
Egorees/algocode_deadline_standings pull request #1
Opened 2024-03-17 14:31 UTC by mrKuznetsov698

2024-03-17 17:09 UTC, MichailKon requested changes

2024-03-17 17:09 UTC, MichailKon commented on server.go
>  		if time.Since(lastUpdate).Seconds() > config.CacheTime {
Звучит как датарейс у lastUpdate (если 2 чела зайдут на страничку и надо будет обновлять данные)
Попробуй использовать github.com/chenyahui/gin-cache

2024-03-17 17:09 UTC, MichailKon commented on server.go
> +			"UsersMap":        mapUsersValues,
Хочется, чтобы челы были отсортированы по фамилии имени

2024-03-19 07:57 UTC, mrKuznetsov698 commented on server.go
> +			"UsersMap":        mapUsersValues,
Сделал, пришлось выбросить мапку и оставить отсорченный slice. Сейчас при таблички для одного юзера поиск за O(N), но т.к. отсортирована сделаю по-позже за O(logN)

2024-03-19 08:21 UTC, merged